### ISSUE TITLE
dropbox - no disk set for backup destination

### ISSUE THREAD

**Issue by w1n78** [spatie/flysystem-dropbox#18]
hello, i am able to do use local without a problem, but when i use dropbox driver i run into errors.

in terminal i get
> Copying zip failed because: There is no disk set for the backup destination.

when i review the email, here's the error it gives me

> Important: An error occurred while backing up Short Term Training Database

Exception message: There is no disk set for the backup destination

Exception trace: #0 /Users/sherwin/apps/laravel/sttdb/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(78): Spatie\Backup\Exceptions\InvalidBackupDestination::diskNotSet() #1 

when i run backup:clean i get a
> invalid driver [dropbox] is not supported

i've checked your blogged, i've destroyed the app api and recreated a new one. i googled issues relating to this and tried different things from those posts. not sure what else i'm missing. please help.

i'm using laravel 5.4.27, mysql 5.7.16

thanks.

**Comment by freekmurze** [comment]
I've just been able to install and setup the package without any problems.

Things to check:
- did you configure a disk named `dropbox` in `config/filesystems.php`
- are you caching your config in local development? If so run `config:clear` to clear the cache.

This issue is more related to spatie/laravel-backup. So if your problems persist, open an issue at that repo. Good luck!

**Comment by w1n78** [comment]
i cleared the cache and the dropbox is configured. i'll open an issue with laravel-backup. thank you.
