### ISSUE TITLE
Empty array when show files within a path

### ISSUE THREAD

**Issue by blackLotus1998** [spatie/flysystem-dropbox#47]
I can display the dropbox folder and files using this spatie/dropbox-api
```php
$client = new \Spatie\Dropbox\Client($authorizationToken);
$folder = $client->listFolder('path');
```
However, using this will ouput me an array without anything

// In laravel
```php
$storage = Storage::disk('dropbox')->files('path');
```

**Comment by Cranavvo** [comment]
I'm also seeing the same. Files/directories exist on dropbox, some paths show files/directories, some don't.

I'm checking Dropbox to see if it's a permission-based issue their side?

**Comment by Doomkyn** [comment]
I'm sorry for resuming this, but I have the same problem, also setup the case_sensitive option, but no luck.
Any tip?

**Comment by Doomkyn** [comment]
The problem is definitely with case sensitivity.
I checked the full flow of dropbox api, and I found out that this function inside `Client.php`

```php
    public function listFolder(string $path = '', bool $recursive = false): array
    {
        $parameters = [
            'path' => $this->normalizePath($path),
            'recursive' => $recursive,
        ];
        return $this->rpcEndpointRequest('files/list_folder', $parameters);
    }
```
returns the path with wrong case.
Even setting the case_sensitive option to false, the problem persist.

In my case, my path is full uppercase, so I tried editing this line 
`$normalizedPath = ltrim($this->removePathPrefix($response['path_display']), '/');`
to
`$normalizedPath = ltrim($this->removePathPrefix(strtoupper($response['path_display'])), '/');`
inside the `normalizeResponse` function of `DropboxAdapter.php` and now it returns the right subfolders.
However, this cannot be the fix because it will not work if I have a non-full uppercase folder.

Hope we can find a fix for this.

**Comment by eusonlito** [comment]
@Doomkyn is not a library problem, is a Dropbox API problem: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/2-files-list-folder-not-consistent-with-results-in-path-display/m-p/208355/highlight/true#M10238

> Unfortunately due to some specifics of how Dropbox is implemented, not all of the path components can be guaranteed to have the expected casing.

Dropbox API is not consistent on case paths on some API endpoints.
